### ISSUE TITLE
dgVoodoo2 Stutter

### ISSUE THREAD

**Issue by MasterLokito** [GenesisFR/DS1TroubleshootingGuide#3]
Hello goodnight. Hope I can post it here. I did the whole process to "Increase UI size" but when I move the mouse the FPS drops drastically. Without using dgVoodoo2 the game works smoothly, however with the tiny UI...
And "if your game crashes at launch or slows down when moving the mouse, disable third-party overlays and frame limiters." not work here...
Can anybody help me?

**Comment by GenesisFR** [comment]
Are you 100% sure you're not using any overlay or frame limiter (even from your GPU control panel)?

**Comment by MasterLokito** [comment]
> Are you 100% sure you're not using any overlay or frame limiter (even from your GPU control panel)?

Hi!
RivaTuner OFF
CapFrameX OFF
V sync  Nvidia Control Panel OFF

I noticed that sometimes when I open the game the problem is solved. I usually need to open it 2 or 3 times and close it, after that it's normal to play.

**Comment by GenesisFR** [comment]
I'm talking about this one.

![image](https://user-images.githubusercontent.com/3614449/225129316-73350c39-aa3f-4659-81dc-1c26f9842910.png)

**Comment by MasterLokito** [comment]
> I'm talking about this one.
> 
> ![image](https://user-images.githubusercontent.com/3614449/225129316-73350c39-aa3f-4659-81dc-1c26f9842910.png)

OFF

Looking in the Voodoo settings I found an option to force v sync on. I turned it off and now it's running fine and smooth.
I don't remember activating this option. I just followed the tutorial and didn't touch anything else...

**Comment by GenesisFR** [comment]
Thanks for investigating, I'll mention turning vsync off.
